.ingest inline into table MigrationConfiguration <|
"DeviceTvmSoftwareInventory","DeviceTvmSoftwareInventoryRaw","None",null,"Full",1
"DeviceTvmSecureConfigurationAssessment","DeviceTvmSecureConfigurationAssessmentRaw","Timestamp",null,"Full",1
"DeviceTvmHardwareFirmware","DeviceTvmHardwareFirmwareRaw","None",null,"Full",1
"DeviceBaselineComplianceProfiles","DeviceBaselineComplianceProfilesRaw","LastUpdatedOn",null,"Full",1
"DeviceBaselineComplianceAssessmentKB","DeviceBaselineComplianceAssessmentKBRaw","None",null,"Full",1
"DeviceBaselineComplianceAssessment","DeviceBaselineComplianceAssessmentRaw","None",null,"Full",1
"DeviceTvmBrowserExtensions","DeviceTvmBrowserExtensionsRaw","InstallationTime",null,"Full",1
"DeviceTvmSoftwareVulnerabilities","DeviceTvmSoftwareVulnerabilitiesRaw","None",null,"Full",1
"DeviceTvmCertificateInfo","DeviceTvmCertificateInfoRaw","None",null,"Full",1
